Homepage Skinning
rocketinsights/algomart-drl pull request #8
Opened 2021-11-05 19:33 UTC by jakerainis

Updates homepage layout and relevant components:

![screencapture-localhost-3000-2021-11-05-15_31_13](https://user-images.githubusercontent.com/658485/140568185-4b9578bb-2d1f-4370-b601-cca6aff3c8dd.png)

2021-11-05 20:50 UTC, nring requested changes

2021-11-05 20:50 UTC, nring commented on apps/web/src/components/releases/release-item.module.css
> +  z-index: 1;
Do you foresee a lot of different z-index values?

2021-11-05 20:50 UTC, nring commented on apps/web/src/components/text-input/text-input.module.css
> +  @apply border border-solid font-light mt-1.5  text-base-gray-dark w-full;
Nitpick: extra space after `mt-1.5`

2021-11-05 20:50 UTC, nring commented on apps/web/src/templates/home-template.tsx
> +        </div>
It might be GitHub's diff viewer, but there's something funky about indentation in this block.

2021-11-05 21:26 UTC, dallashuggins approved these changes
Looking great! Not seeing any issues aside from `npm run format` picked up on some things, but not from this branch. 

Is there a Figma file I should reference? I can more closely compare with the designs if helpful.

2021-11-05 21:26 UTC, dallashuggins commented on apps/web/src/templates/home-template.tsx
> +        </div>
I think it may be the viewer, because I'm not seeing anything weird here. But the `npm run format` did pick up on some formatting issues, I don't think from this branch though.

2021-11-05 21:39 UTC, jakerainis commented on apps/web/src/templates/home-template.tsx
> +        </div>
Yeah I think it's GH's viewer. Seems okay in the file (prettier applied as well).

<img width="849" alt="Screen Shot 2021-11-05 at 5 04 05 PM" src="https://user-images.githubusercontent.com/658485/140581594-21713b50-a825-4556-9e75-ccf0f6641b24.png">

2021-11-05 21:46 UTC, jakerainis commented on apps/web/src/components/releases/release-item.module.css
> +  z-index: 1;
Thanks for calling this out. I actually made it a variable because I could see it being handy elsewhere in the future. 

To answer your question, [this is what Tailwind gives us OOTB](https://tailwindcss.com/docs/z-index), which is sufficient for what we've needed. As far as layer complexity goes, we have this from lowest z to highest z:
- Base things
- [newly added] pack badge that just needs to surface the image its adjacent to
- Select box
- Global Nav
- Modal Dialog

I don't foresee us adding anything else that couldn't fit between these.

2021-11-05 21:47 UTC, jakerainis commented on apps/web/src/components/text-input/text-input.module.css
> +  @apply border border-solid font-light mt-1.5  text-base-gray-dark w-full;
Thanks for nothing Prettier. 😆 

Fixed!

2021-11-08 14:37 UTC, nring approved these changes
👍

2021-11-08 15:15 UTC, merged